spring:
  application.name: config-server
server:
  port: 8888

spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/pzwdshxzt/platform
          searchPaths: config-repo
          username:
          password:
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:${eureka.port}/eureka/