eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3:9999/eureka/,http://eureka2:9998/eureka/,http://eureka1:9997/eureka/

server:
  port: 8081

spring:
  application:
    name: platform-client