server:
  port: 9997

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: eureka1
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka2:9998/eureka/,http://eureka3:9999/eureka/

