spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 5001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3:9999/eureka/
